spring:
  security:
    oauth2:
      client:
        provider:
          kakao:
            # 인가코드 받기
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            # 토큰 받기
            token-uri: https://kauth.kakao.com/oauth/token
            # 사용자 정보 가져오기
            user-info-uri: https://kapi.kakao.com/v2/user/me
            # 응답에서 적당한 key 가져오기
            user-name-attribute: id

        registration:
          kakao:
            # REST API 키
            client-id: 72246d6f047747ec64f19bd2e88d7e97
            # Client Secret
            client-secret: YDmhTAW3HudxOLZDUu3hEXGDelsIPyKZ
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            # naver랑 똑같이 써주면 됨
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email

  datasource:
    #    pc에 만들어 놓은 DataBase 이름을 써야한다.
    url: jdbc:mysql://localhost:3306/recipe
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hoon
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always